---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
setwd("E:/RA/Pablo Moscato/Code/R Code")

# rm(list=ls()) #Code to clear all variables
library("TSP")
library("optrees")
library("matrixcalc")
library("tidyr")
# install.packages("matrixcalc")
concordePath = "E:/RA/Pablo Moscato/Concorde_Code/"
concorde_path(concordePath)
concorde_help()
print("done")
```

```{r main}
dataset_path = "E:/RA/Pablo Moscato/dataset/FHCPCS/"

############################# hcp dataset reading logic #####################################
start_itter = 21
emd_itter = 50
for (q in start_itter:emd_itter){
  print(paste("Iteration Number: ",q))
  # name = "graph1.hcp"
  name = paste("graph",q,".hcp",sep = "")
  file_name = paste(dataset_path,name,sep = "")
  # dataset_hcp = read.table(file_name, header = FALSE, sep = "", dec = ".")
  dataset_hcp = read.delim(file_name)
  dataset_hcp = dataset_hcp[-c(1:5),]
  dataset_hcp_2 = data.frame(dataset_hcp)
  dataset_hcp_2 = data.frame(dataset_hcp_2[-c((nrow(dataset_hcp_2)-1):(nrow(dataset_hcp_2))),])
  colnames(dataset_hcp_2)<-"x1"
  dataset <- separate(data = dataset_hcp_2, col = x1, into = c("x1", "x2"), sep = "\\ ")
  ############################# hcp dataset reading logic #####################################
  adj_new_final = farthest_inserion_cheapest_selection(dataset)
  
  
  ########################## Concorde Logic Starts Here #########################
  # dataset <- adj_new_final
  final_edgelist = adj_new_final
  
  
  g2 <- graph_from_edgelist(as.matrix(final_edgelist),directed = FALSE)
  plot(g2,main = name)
  d <- (1/as_adjacency_matrix(g2, sparse = FALSE))-1
  d[d==Inf] = 3.99990099
  d[d<3.99990099] = 0
  tsp <- TSP(d)
  # o2 <- solve_TSP(tsp, method="concorde",rep=10, control = list(clo = "-V"))
  o3 <- solve_TSP(tsp, method="concorde",rep=10)
  print(o3)
  # as.integer(o3)
}
########################## Concorde Logic Ends Here #########################
```

```{r functions}
farthest_inserion_cheapest_selection = function(dataset_fun){

  dataset_fun <- as.data.frame(sapply(dataset_fun, as.numeric)) #<- character to integer conversion
  final_graph = dataset_fun
  
  g <- graph_from_edgelist(as.matrix(final_graph),directed = FALSE)
  # plot(g)
  
  adj_mat = as_adjacency_matrix(g, sparse = FALSE)
  dijkstra_matrix <- shortest.paths(g, algorithm = "dijkstra")
  
  
  
  # farthest_path = as.matrix(unlist(get_diameter(g, unconnected=FALSE)))
  farthest_path = matrix(0,3,1)
  farthest_path[1,1] = 1
  farthest_path[2,1] = 3
  farthest_path[3,1] = 1
  
  
  Total_nodes = length(degree(g))
  Total_nodes2 = 1:Total_nodes
  # 
  # if(length(farthest_path)!=Total_nodes){
  node_length = 0
    while (node_length!=Total_nodes+1){
      
      ################### Farthest Node Selection (start)##########################
      dijkstra_matrix_3 = dijkstra_matrix
      dijkstra_matrix_3[farthest_path[,1],farthest_path[,1]] = 0 # making the distance 0 for those pairs who are already in the sub-tour
      
      # which(dijkstra_matrix_3 == max(dijkstra_matrix_3), arr.ind = TRUE)
      sub_dist_mat = dijkstra_matrix[unique(farthest_path),]
      sub_dist_mat[,unique(farthest_path)] = 0
      col_sum_sub_dist_mat = colSums(sub_dist_mat)
      node_to_be_added = which.max(col_sum_sub_dist_mat)
      
      ################### Farthest Node Selection (end)##########################
      
      ################### cheapest Node insertion (start)##########################
      min_dist = dijkstra_matrix[node_to_be_added,farthest_path]
      min_dist = as.matrix(t(min_dist))
      colnames(min_dist) = c(paste(farthest_path))
      
      dist_mat = matrix(0,length((farthest_path))-1,4)
      colnames(dist_mat) = c("d_{c_i}","d_{c_j}","d_{ij}","d_{c_i}+d_{c_j}-d_{ij}")
      
      dist_mat[,1] = min_dist[1:(length(min_dist)-1)]
      dist_mat[,2] = min_dist[2:(length(min_dist))]
      
      c_1 = farthest_path[1:(length(min_dist)-1)]
      c_2 = farthest_path[2:(length(min_dist))]
      names = NULL
      for(i in 1:(length(min_dist)-1)){
        dist_mat[i,3] = dijkstra_matrix[c_1[i],c_2[i]]
        names = c(names,paste("Nodes -> (",c_1[i],",",c_2[i],")"))
      }
      rownames(dist_mat) = names
      
      
      dist_mat[,4] = (dist_mat[,1] + dist_mat[,2]) - dist_mat[,3]
      ind_1 = which.min(dist_mat[,4])
      ind_2 = ind_1+1
      
      farthest_path_2 = matrix(0,length(farthest_path[,1])+1,1)
      farthest_path_2[1:ind_1,1] = farthest_path[1:ind_1,1]
      farthest_path_2[ind_1+1,1] = node_to_be_added
      farthest_path_2[ind_2:length(farthest_path[,1])+1,1] = farthest_path[ind_2:length(farthest_path[,1]),1]
      farthest_path = farthest_path_2
      
      ################### cheapest Node insertion (end)##########################
      node_length = length(farthest_path)
      # print(t(farthest_path))
      # print(paste("Node Length = ",node_length))
    }
  # }
  # t(farthest_path)
  
  adj_new = matrix(0,(length(farthest_path)-1),2)
  for(i in 1:(length(farthest_path)-1)){
      adj_new[i,1] = farthest_path[i]
      adj_new[i,2] = farthest_path[i+1]
  }
  return(adj_new)
} #function ends here

```





